const Discord = require("discord.js");
module.exports.run = (client, message, args) => {
  let mention = message.mentions.users.first() || message.author
  let user = message.author
  let lastmsg;
  let game;
  if (mention.lastMessage === null) {
    lastmsg = "User didn't send a message"
  } else {
    lastmsg = mention.lastMessage
  }
  if (mention.presence.game === null) {
    game = "User is not playing a game"
  } else {
    game = mention.presence.game.name
  }
  const embed1 = new Discord.RichEmbed()
  .setColor('RANDOM')
  .setAuthor(`Info for ${mention.username}`, mention.displayAvatarURL)
  .setThumbnail(mention.displayAvatarURL)
  .setFooter(`This is generated by ${client.user.tag}`, client.user.avatarURL)
  .addField(`Info for ${mention.username}`, `**User ID**: ${mention.id}\n**User Discriminator**: ${mention.discriminator}\n**Last message**: ${lastmsg}\n**User Status**: ${mention.presence.status}\n**User Playing**: ${game}\n**Account created on**: ${mention.createdAt}`)
  message.channel.send({embed : embed1})
};

exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: ["ui"],
  permLevel: "Moderator"
};

exports.help = {
  name: "userinfo",
  description: "Gives some useful user info",
  usage: "userinfo [mention]"
};